version: '3.8'

services:
  # MongoDB container
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    env_file:
      - mongo.env

  # Server container
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - server.env

  # Client container
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - client.env