[tool.poetry]
name = "server"
version = "0.1.0"
description = "CampusHub backend"
authors = ["Jae Aeich <jh4official@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
connexion = {extras = ["flask", "swagger-ui", "uvicorn"], version = "^3.0.5"}
gunicorn = "^21.2.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
