ServiceList:
  type: array
  items:
    $ref: '#/Service'

Service:
  type: object
  properties:
    service_id:
      type: string
    store_ids:
      type: array
      items:
        type: string
    service_name:
      type: string
    service_description:
      type: string
      nullable: true
    service_images:
      type: array
      items:
        type: string
    service_categories:
      type: array            
      items:
        type: string

parameters:
  name: service_id
  in: path
  description: Service ID
  required: true
  schema:
    $ref: "#/Service/properties/service_id" 

        