name: Client CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Client Dependencies
        run: |
          cd client
          npm ci

      - name: Lint Client Code
        run: |
          cd client
          npm run lint

      - name: Check Code Formatting in Client
        run: |
          cd client
          npm run format:check
