name: Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install Vercel CLI
        run: npm install --global vercel@latest

      # - name: pull Vercel environment information
      #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # - name: build project artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # - name: deploy preview + assign beta domain
      #   run: |
      #     cd client
      #     OUTPUT=$(du --inodes -d 5 .vercel/output)
      #     echo "$OUTPUT"
      #     LAST=$(echo "$OUTPUT" | tail -n 1)
      #     PERCENTAGE=$(echo "$LAST" | awk 'BEGIN {maxtotal=15000} { printf "%.2f%%", ($1/maxtotal*100) }')
      #     echo "Vercel file usage percentage" >> $GITHUB_STEP_SUMMARY
      #     echo "$PERCENTAGE" >> $GITHUB_STEP_SUMMARY
      #     du -h -d 3 .vercel/output/functions/en
      #     vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
      #     vercel alias --scope ${{ secrets.VERCEL_TEAM_ID }} --token ${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` biodrop-preview.vercel.app
